# Generated by Django 4.2.3 on 2023-08-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_category_options_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='power_hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
